CREATE DATABASE BURGERS_DB;
USE BURGERS_DB;

CREATE TABLE BURGERS
(
	ID INT NOT NULL AUTO_INCREMENT,
	BURGER_NAME varchar(50) NOT NULL,
	DEVOURED BOOLEAN DEFAULT false,
	DATE TIMESTAMP,
	PRIMARY KEY (id)
);
