INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('Bacon Cheeseburger', false);
INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('Black and Blue Bacon Burger', true);
INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('Chilli Burger', true);

