-- CREATE DATABASE FITREP_DB;
-- USE FITREP_DB;

INSERT INTO NEWUSERS (FIRST_NAME, LAST_NAME, HEIGHTFT, HEIGHTIN WEIGHT, AGE, EMAIL) VALUES ('Ryan', 'Cowles', '6', '0', '200', '25', 'rcowles3@gmail.com');


